# Generated by Django 5.1.6 on 2025-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(),
        ),
    ]
